server:
  port: 9711

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: michael
    password: 1101
    url: jdbc:mariadb://localhost:3306/devplace
  thymeleaf:
    cache: false # ?? ?? reload

  #JPA??
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none